# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.3.0
#     hooks:
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
# -   repo: https://github.com/psf/black
#     rev: 19.3b0
#     hooks:
#     -   id: black
repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.1
    hooks:
    -   id: checkmake
-   repo: https://github.com/golangci/golangci-lint
    rev: master
    hooks:
    -   id: golangci-lint

default_language_version:
    python: python3.8
