package parser

import (
	"os"
	"testing"

	clog "github.com/proffer/common/clogger"
)

func TestMain(m *testing.M) {
	// disabling logging
	clog.SetGlobalLogLevel(clog.NONE)

	// create dummy file with no permission for one of test cases
	file, _ := os.Create("../test/invalid_yml/no_read_permission.yml")
	_ = file.Chmod(0000)

	// Run the tests
	statusCode := m.Run()

	// clean temp file generated by test execution
	_ = os.Remove("output.yml")
	_ = file.Chmod(0666)

	file.Close()

	_ = os.Remove("../test/invalid_yml/no_read_permission.yml")

	os.Exit(statusCode)
}
