package cmd

import (
	"os"
	"testing"

	clog "github.com/proffer/common/clogger"
)

func TestMain(m *testing.M) {
	// disabling logging
	clog.SetGlobalLogLevel(clog.NONE)

	// Run the tests
	statusCode := m.Run()

	// clean temp file generated by test execution
	_ = os.Remove("output.yml")
	os.Exit(statusCode)
}
