name: Lint GO Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check go version
        run: go version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for unformatted go code
        run: fmt-check

      - name: Check for unused go dependencies
        run: tidy-check

      - name: Lint Go Code
        run: make ci-lint
